---
# default variables for lab environments
ec2_name_prefix: test-demo
ec2_region: us-west-2
ec2_wait: yes
ec2_az: "{{ec2_region}}a"
ec2_subnet: "172.16.0.0/16"
ec2_subnet2: "172.17.0.0/16"
ec2_security_group: "{{ ec2_name_prefix }}-insecure_all"
ssh_port: 22
rhel: rhel7
ec2_info:
  rhel7:
    owners: 309956199498
    size: t2.micro
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-7.4*GA*'
    username: ec2-user
key_dir: "{{ playbook_dir }}/roles/aws-lab/files/aws-key.pub"
